apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  namespace: rajapp1  # This will be overridden dynamically by ArgoCD
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: app1-container
          image: nginx:latest
          ports:
            - containerPort: 80


