apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: two-git-sources
  namespace: argocd
spec:
  project: default
  destination:
    server: https://target-vcluster.gartner.opsmx.net:443
    namespace: argocd-kt
  sources:
    - repoURL: https://github.com/OpsMx/argo-customer-demo.git
      path: datas/git/two-git-source/git1
      targetRevision: HEAD
    - repoURL: https://github.com/OpsMx/argo-customer-demo.git
      path: datas/git/two-git-source/git2
      targetRevision: HEAD
