# this generator i use for one git source and one helm source
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: git-application-set
  namespace: argocd
spec:
  generators:
    - git:                 
        repoURL: "https://github.com/OpsMx/argo-customer-demo.git"
        revision: "HEAD"
        directories:
          - path: "datas/application-set-date/git-data/*"
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: "https://github.com/OpsMx/argo-customer-demo.git"
        targetRevision: "HEAD"
        path: '{{path}}'
      destination:
        server: "https://target-vcluster.gartner.opsmx.net:443"
        namespace: 'argocd-kt'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
