apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: raj-matrix-helm
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - appName: two-helm1
                - appName: two-helm2
          - list:
              elements:
                - name: helm-app1
                  valuesPath: "helm-values/matrix1/two-helm/helm-app1/values.yaml"
                - name: helm-app2
                  valuesPath: "helm-values/matrix2/two-helm/helm-app2/values.yaml"
  template:
    metadata:
      name: '{{appName}}-{{name}}'
    spec:
      project: default
      source:
        repoURL: "https://github.com/Rajesh-Sangepu/argocd-app-bitthal.git"
        targetRevision: "HEAD"
        path: "application-set/matrix-generator-using-helm"
        helm:
          valueFiles:
            - "{{valuesPath}}"
      destination:
        server: "https://kubernetes.default.svc"
        namespace: '{{appName}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
