apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: raj-matrix-generator
spec:
  generators:
    - matrix:
        generators:
         - list:
              elements:
                - appName: app1
                - appName: app2
          - git:                 
              repoURL: "https://github.com/Rajesh-Sangepu/argocd-app-bitthal.git"
              revision: HEAD
              directories:
                - path: "application-set/git-data/*"
  template:
    metadata:
      name: '{{appName}}-{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/Rajesh-Sangepu/argocd-app-bitthal.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: "https://kubernetes.default.svc"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
