apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: matrix-generator-list-git
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - appName: matrix-app0
                - appName: matrix-app1
          - list:
        elements:
          - name: matrix-application-set-app1
            repoURL: https://github.com/Rajesh-Sangepu/argocd-app-bitthal.git          #pod
            targetRevision: HEAD
            path: application-set/matrix-data/matrix-appset1
          - name: matrix-application-set-app2
            repoURL: https://github.com/Rajesh-Sangepu/argocd-app-bitthal.git           #service
            targetRevision: HEAD
            path: application-set/matrix-data/matrix-appset2
  template:
    metadata:
      name: '{{appName}}-{{name}}'
    spec:
      project: default
      source:
        repoURL: "https://github.com/OpsMx/argo-customer-demo.git"
        targetRevision: "HEAD"
        path: "{{path}}"
      destination:
        server: "https://target-vcluster.gartner.opsmx.net:443"
        namespace: '{{appName}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
