apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: raj-matrix-git-list-cluster
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/Rajesh-Sangepu/argocd-app-bitthal.git
              revision: main
              directories:
                - path: application-set/matrix-data/*
          - list:
              elements:
                - env: dev-vcluster
                  namespace: raj-dev-apps
                  server: https://dev-vcluster.opencd.opsmx.org:443
                - env: in-cluster
                  namespace: in-cluster-apps
                  server: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{path | basename}}-{{env}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/Rajesh-Sangepu/argocd-app-bitthal.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: '{{server}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
