apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applicationset-matrix
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - git:                 
            repoURL: "https://github.com/Rajesh-Sangepu/argocd-app-bitthal.git"
            revision: "HEAD"
            directories:
              - path: "application-set/matrix-data/*"
          - list:
              elements:
                - cluster: https://kubernetes.default.svc
                  namespace: app-one-namespace
                - cluster: https://kubernetes.default.svc
                  namespace: app-two-namespace
  template:
    metadata:
      name: '{{name}}-{{namespace}}'
    spec:
      project: default
      source:
        repoURL: "https://github.com/Rajesh-Sangepu/argocd-app-bitthal.git"
        targetRevision: "HEAD"
        path: "application-set/matrix-data/*"
      destination:
        server: "https://kubernetes.default.svc"
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
