apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: raj-matrix-applicationset
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - appName: app0
                - appName: app1
          - list:
              elements:
                - name: app0
                  path: "application-set/matrix-data/matrix-appset1"
                - name: app1
                  path: "application-set/matrix-data/matrix-appset2"
  template:
    metadata:
      name: '{{appName}}-{{name}}'
    spec:
      project: default
      source:
        repoURL: "https://github.com/Rajesh-Sangepu/argocd-app-bitthal.git"
        targetRevision: "HEAD"
        path: "{{path}}"  
      destination:
        server: "https://kubernetes.default.svc"
        namespace: '{{appName}}'
      syncPolicy:
        automated:
          prune: false
          selfHeal: false
        syncOptions:
          - CreateNamespace=true
