apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: raj-matrix-git-list-cluster
spec:
  generators:
    - matrix:
        generators:
         - list:
              elements:
                - appName: app1
                - appName: app2
        - list:
            elements:
              - name: list-application-set-app1
                repoURL: https://github.com/Rajesh-Sangepu/argocd-app-bitthal.git          #pod
                targetRevision: HEAD
                path: application-set/list-data/app1
              - name: list-application-set-app2
                repoURL: https://github.com/Rajesh-Sangepu/argocd-app-bitthal.git           #service
                targetRevision: HEAD
                path: application-set/list-data/app2
  template:
    metadata:
      name: '{{appName}}-{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/Rajesh-Sangepu/argocd-app-bitthal.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: "https://kubernetes.default.svc"
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
