apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: matrix-generator-list-git
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - cluster: dev
                  url: https://dev-vcluster.opencd.opsmx.org:443
                - cluster: staging
                  url: https://kubernetes.default.svc
          - git:
              repoURL: https://github.com/Rajesh-Sangepu/argocd-app-bitthal.git
              revision: HEAD
              directories:
                - path: application-set/matrix-data/*
  template:
    metadata:
      name: "{{cluster}}-{{path.basename}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/Rajesh-Sangepu/argocd-app-bitthal.git
        targetRevision: HEAD
        path: "{{path}}"
      destination:
        server: "{{url}}"
        namespace: my-apps
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
