apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: matrix-generator-list-git
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - app: frontend
                - app: backend
          - git:
              repoURL: https://github.com/Rajesh-Sangepu/argocd-app-bitthal.git
              revision: HEAD  # ✅ Correct field name
              directories:
                - path: application-set/matrix-data/matrix-appset1
                - path: application-set/matrix-data/matrix-appset2
  template:
    metadata:
      name: "{{app}}-{{path.basename}}"  # Generates names like "frontend-matrix-appset1"
    spec:
      project: default
      source:
        repoURL: https://github.com/Rajesh-Sangepu/argocd-app-bitthal.git
        targetRevision: HEAD
        path: "{{path}}"  # Uses directory from Git generator
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{app}}-namespace"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
