apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: matrix-git-list-cluster-example
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/example-org/example-repo.git
              revision: main
              directories:
                - path: apps/app1
                - path: apps/app2
          - list:
              elements:
                - env: dev
                  namespace: dev-apps
                  server: https://dev-cluster.example.com
                - env: prod
                  namespace: prod-apps
                  server: https://prod-cluster.example.com
  template:
    metadata:
      name: '{{path | basename}}-{{env}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/example-org/example-repo.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: '{{server}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
