apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: image-updater-helm
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: "bitthalpatidar/my-repo:1.2.*"
    argocd-image-updater.argoproj.io/my-repo.update-strategy: "latest"
    argocd-image-updater.argoproj.io/write-back-method: "git:secret:argocd/git-creds-new"
spec:
  project: default
  source:
    repoURL: 'https://github.com/OpsMx/argo-customer-demo.git'
    path: 'datas/image-updater-data'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://target-vcluster.gartner.opsmx.net:443'
    namespace: argocd-kt
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
